{'_id': '10612199', 'listing_url': 'https: //www.airbnb.com/rooms/10612199', 
 'name': 'Serene luxury in Harlem', 
 'summary': 'Lovely 1500sqft gem located in Central Harlem close to Columbia University. Gorgeous Pre-war flat with 6ft ceilings, 2 fireplaces, and laundry in the unit. Located in a safe, friendly building and close to major restaurants and subway lines.', 
 'space': '', 
 'description': 'Lovely 1500sqft gem located in Central Harlem close to Columbia University. Gorgeous Pre-war flat with 6ft ceilings, 2 fireplaces, and laundry in the unit. Located in a safe, friendly building and close to major restaurants and subway lines. Very short walking distance to restaurants, bars, supermarket, pharmacy, cafes, and movie theaters. Only 10 minute walk to Columbia University. Just a few short blocks to the A-B-C-D-2-3 subway lines. A-D-2-3 are express trains. Lots of bus lines nearby, as well.', 
 'neighborhood_overview': 'Very short walking distance to restaurants, bars, supermarket, pharmacy, cafes, and movie theaters. Only 10 minute walk to Columbia University.', 
 'notes': '', 
 'transit': 'Just a few short blocks to the A-B-C-D-2-3 subway lines. A-D-2-3 are express trains. Lots of bus lines nearby, as well.', 
 'access': '', 'interaction': '', 'house_rules': 'Quiet time after 10pm and keep common areas tidy.', 
 'property_type': 'Apartment', 'room_type': 'Private room', 'bed_type': 'Real Bed', 
 'minimum_nights': '3', 'maximum_nights': '1125', 'cancellation_policy': 'moderate', 
 'last_scraped': (2019, 3, 7, 5, 0), 
 'calendar_last_scraped': (2019, 3, 7, 5, 0), 
 'first_review': (2016, 8, 13, 4, 0), 
 'last_review': (2019, 1, 5, 5, 0), 
 'accommodates': 1, 
 'bedrooms': 1, 
 'beds': 1, 
 'number_of_reviews': 10, 
 'bathrooms': ('1.0'), 
 'amenities': ['Wifi', 'Air conditioning', 'Kitchen', 'Elevator', 'Buzzer/wireless intercom', 'Heating', 'Washer', 'Essentials', 'Hangers', 'Hair dryer', 'Iron', 'Laptop friendly workspace', 'Bed linens', 'Extra pillows and blankets'], 
 'price': ('80.00'), 
 'security_deposit': ('100.00'), 
 'cleaning_fee': ('50.00'), 
 'extra_people': ('0.00'), 
 'guests_included': ('1'), 
 'images': {'thumbnail_url': '', 
            'medium_url': '', 
            'picture_url': 'https://a0.muscache.com/im/pictures/84254dd0-e266-4345-afcc-e8f7c56f4634.jpg?aki_policy=large', 'xl_picture_url': ''}, 
 'host': {'host_id': '54761069', 
          'host_url': 'https://www.airbnb.com/users/show/54761069', 
          'host_name': 'Erika', 
          'host_location': 'New York, New York, United States', 
          'host_about': '', 'host_response_time': 'within an hour', 
          'host_thumbnail_url': 'https://a0.muscache.com/im/pictures/8f1942a1-dde8-4733-aff6-5971a0678594.jpg?aki_policy=profile_small', 
          'host_picture_url': 'https://a0.muscache.com/im/pictures/8f1942a1-dde8-4733-aff6-5971a0678594.jpg?aki_policy=profile_x_medium', 
          'host_neighbourhood': 'Harlem', 
          'host_response_rate': 100, 
          'host_is_superhost': False, 
          'host_has_profile_pic': True, 
          'host_identity_verified': True, 
          'host_listings_count': 1, 
          'host_total_listings_count': 1, 
          'host_verifications': ['email', 'phone', 'facebook', 'reviews', 'kba']}, 
 'address': {'street': 'New York, NY, United States', 
             'suburb': 'Manhattan', 
             'government_area': 'Harlem', 
             'market': 'New York', 
             'country': 'United States', 
             'country_code': 'US', 
             'location': {'type': 'Point', 'coordinates': [-73.95211, 40.80708], 'is_location_exact': True}}, 
 'availability': {'availability_30': 5, 
                  'availability_60': 35, 
                  'availability_90': 65, 
                  'availability_365': 339}, 
 'review_scores': {'review_scores_accuracy': 10, 
                   'review_scores_cleanliness': 10, 
                   'review_scores_checkin': 10, 
                   'review_scores_communication': 10, 
                   'review_scores_location': 10, 
                   'review_scores_value': 10, 
                   'review_scores_rating': 100}, 
 'reviews': [{'_id': '93734315', 
              'date': (2016, 8, 13, 4, 0), 
              'listing_id': '10612199', 
              'reviewer_id': '54401890', 
              'reviewer_name': 'Ashlie', 
              'comments': 'Erika was extremely friendly, kind, and caring while I stayed there. She made me feel at home! She knows the area very well and can provide information about things to do and places to eat in the neighborhood.\r\n\r\nThe area is also quite safe and it is not uncommon to hear kids playing outside at 9 pm or later.\r\n\r\nThe apartment is a few minutes walk from a good-sized grocery store, numerous restaurants, multiple subway stations, and Central Park, making it an ideal place to stay while visiting.'}, 
             {'_id': '103823581', 
              'date': (2016, 9, 24, 4, 0), 
              'listing_id': '10612199', 
              'reviewer_id': '33981348', 
              'reviewer_name': 'Alice', 
              'comments': "I stayed with Erica for 2 weeks and it was great! When I arrived at Erica's I was greeted by her delightful son as she was sunning it up on a beautiful beach! I was free to do what I want and when I want. The room was spotless and so comfy - I felt right at home. Amazing stay, I would definitely recommend staying here. "}, 
             {'_id': '108103645', 
              'date': (2016, 10, 14, 4, 0), 
              'listing_id': '10612199', 
              'reviewer_id': '44597213', 
              'reviewer_name': 'Tiffany', 
              'comments': "True to the description, Erika's place is an oasis of serenity in the city. Erika was a great host and really extended herself to make sure I was comfortable and felt welcome. Her apartment is absolutely lovely, spacious, very clean and tidy, as is the room. The apartment is just a few steps away from subway stations, restaurants and a great grocery store. Staying with Erika and her son was a wonderful experience; they are both lovely people. I had a great stay and would highly recommend.\r\n\r\nAlso, Erica makes a mean cup of Italian coffee.  If you stay with her, don't miss it! "}, 
             {'_id': '120316952', 
              'date': (2016, 12, 9, 5, 0), 
              'listing_id': '10612199', 
              'reviewer_id': '97297055', 
              'reviewer_name': 'Mònica', 
              'comments': 'Erika is a very good hostess, very friendly and polite.\nHis house is cozy and clean.\nThe area is quiet and close to subway.\nDefinitely the best choice for a nice stay in NY!\n'}, 
             {'_id': '164512500', 
              'date': (2017, 6, 27, 4, 0), 
              'listing_id': '10612199', 
              'reviewer_id': '113006262', 
              'reviewer_name': 'Benjamin', 
              'comments': 'I stayed with Erika and Brandon for 5 months and I had the most amazing experience of my life. I would strongly suggest staying with them for long or short visits. The apartment was always clean and larger than the photos made it look. Erika helped me sort any problems that I had throughout my stay and with Brandon there, there was never a dull moment. I have made friends for life and hope to see them again soon. '}, 
             {'_id': '258172600', 
              'date': (2018, 4, 28, 4, 0), 
              'listing_id': '10612199', 
              'reviewer_id': '24882427', 
              'reviewer_name': 'Angel', 
              'comments': "Erika's stylish and welcoming Harlem home was the perfect place for me while I was transitioning out of New York. Erika is an awesome host (thank you again for the great conversation and the coffee), her house is a 5 minute walk to the ABCD trains, and there are so many great places to visit in her neighborhood. I stayed with Erika for 8 days, and my stay was exactly what I needed: a safe, quiet place to sleep that is not too far away from my job/school and close to public transportation. Thank you again Erika!"}, 
             {'_id': '261461524', 
              'date': (2018, 5, 6, 4, 0), 
              'listing_id': '10612199', 
              'reviewer_id': '34754875', 
              'reviewer_name': 'Patrick', 
              'comments': "Words fail to adequately describe how amazing Erika is. Not only was her apartment and the room amazing, but Erika went above and beyond making me feel at ease and welcomed. She made a nice breakfast and killer coffee, and she even woke up before sunrise just to ensure I didn't sleep through my alarm for an early flight! \n\nBeyond being a great host,  Erika is one of the most honest and thoughtful people I've ever had the fortune of meeting. I will certainly be visiting, if not staying with, her the next time I'm in NY!"}, 
             {'_id': '268039374', 'date': (2018, 5, 23, 4, 0), 
              'listing_id': '10612199', 
              'reviewer_id': '3118982', 
              'reviewer_name': 'Mauricio', 
              'comments': "Erika's place is very well located in the vibrant Harlem, close to public transport, nice restaurants and coffee shops.\nThe house is actually bigger than it look in the pictures and Erika and her son Brandon made everything to make my stay pleasant. I would definitely recommend!"}, 
             {'_id': '309738614', 
              'date': (2018, 8, 18, 4, 0),                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
              'listing_id': '10612199', 
              'reviewer_id': '184468043',                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'reviewer_name': 'Riley', 'comments': 'I had a truly wonderful stay! Erika is a great host, she was so kind and gracious and incredibly helpful. I can’t say enough good things about Erika and her home! '}, 
             {'_id': '367828248', 'date':(2019, 1, 5, 5, 0), 
              'listing_id': '10612199', 
              'reviewer_id': '24064977', 
              'reviewer_name': 'Gabriel', 
              'comments': "I had the privilege to stay with Erika for a whole semester and I can only say that this amazing experience would have never been the same without her. She is the warmest and most understanding person I know She is always there for you and really makes you feel like you're at home."}]}